### ISSUE TITLE
compile failure: memset overflows destination (-Werror=stringop-overflow)

### ISSUE THREAD

**Issue by jwdevel** [exeldro/obs-move-transition#243]
I recently tried to build this plugin standlone, on Debian Linux, and hit a compile error (or rather: warning-treated-as-error).

Here is my session:

```
$ cmake -S . -B build -DBUILD_OUT_OF_TREE=On && cmake --build build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jrw/dev/external/obs-move-transition/build
[ 10%] Building C object CMakeFiles/move-transition.dir/move-filter.c.o
In file included from /usr/include/obs/util/profiler.h:4,
                 from /usr/include/obs/obs.h:22,
                 from /usr/include/obs/obs-module.h:20,
                 from /home/jrw/dev/external/obs-move-transition/move-transition.h:3,
                 from /home/jrw/dev/external/obs-move-transition/move-filter.c:1:
In function ‘darray_push_back_new’,
    inlined from ‘move_filter_update’ at /home/jrw/dev/external/obs-move-transition/move-filter.c:360:17:
/usr/include/obs/util/darray.h:210:9: error: ‘memset’ writing 60 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  210 |         memset(last, 0, element_size);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘darray_push_back_new’,
    inlined from ‘move_filter_update’ at /home/jrw/dev/external/obs-move-transition/move-filter.c:414:17:
/usr/include/obs/util/darray.h:210:9: error: ‘memset’ writing 60 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  210 |         memset(last, 0, element_size);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
gmake[2]: *** [CMakeFiles/move-transition.dir/build.make:104: CMakeFiles/move-transition.dir/move-filter.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/move-transition.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

I don't know if this is a false alarm, or real problem (I'm not familiar with this codebase).

Environment info:

* changeset: 0f97047
* OBS version: 29.0.2.1-1+b1 (linux)  
* gcc: Debian 12.2.0-14

**Comment by jwdevel** [comment]
I bisected this, and it was introduced in bf93acb.

(I guess that makes sense, since that's when the code with the warning was added)

The last tagged release that builds with no problem for me is 3.0.2.
